apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: api-app
          image: api-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              value: "host"
            - name: POSTGRES_PASSWORD
              value: "test"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_HOST
              value: "SET IP"
            - name: POSTGRES_DB
              value: "main"
            - name: debug_mode
              value: "true"
            - name: REDIS_PASSWORD
              value: "test"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_HOST
              value: "SET IP"


---
apiVersion: v1
kind: Service
metadata:
  name: api-app
spec:
  type: LoadBalancer
  selector:
    app: api-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000