apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: api-app
          image: 'gcr.io/semiotic-joy-438622-r2/api-website:latest'
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: config-map-api-website
      restartPolicy: Always  # Ensure restartPolicy is Always for Deployments

---
apiVersion: v1
kind: Service
metadata:
  name: api-app
spec:
  type: LoadBalancer
  selector:
    app: api-app
  ports:
    - protocol: TCP
      name: http-svc
      port: 80
      targetPort: 8000
